@baseUrl =  http://localhost:8000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGxvY2FsLmlvIiwiaWF0IjoxNjgxNjc2ODM4fQ.-0WfQEWFTb-zHJTwUzds4d0UWlPiaabGKuLsF2O27SM

# Signup
POST {{baseUrl}}/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "admin@local.io",
  "name": "Vitalii",
  "password": "123456"
}
###


# Signin
POST {{baseUrl}}/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "admin@local.io",
  "password": "123456"
}
###

# User info
GET {{baseUrl}}/users/info HTTP/1.1
Authorization: {{token}}

###

# Create topic
POST {{baseUrl}}/topics HTTP/1.1
Content-Type: application/json

{
  "name": "Электроника"
}
###

# Get topics
GET {{baseUrl}}/topics HTTP/1.1

###

# Create tag
POST {{baseUrl}}/tags HTTP/1.1
Content-Type: application/json

{
  "name": "Красный"
}
###

# Get topics
GET {{baseUrl}}/tags HTTP/1.1

###

# Create city
POST {{baseUrl}}/cities HTTP/1.1
Content-Type: application/json

{
  "name": "Владивосток"
}
###

# Get cities
GET {{baseUrl}}/cities HTTP/1.1

###

# Create offer
POST {{baseUrl}}/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Владивосток 3332",
  "description": "Cупер новое предложение 2",
  "url": "https://www.ozon.ru",
  "startAt": "2023-04-24T14:48:00.000Z",
  "endAt": "2023-04-29T14:48:00.000Z",
  "cityId": 1,
  "topicId": 1,
  "tags": [1,2]
}
###

# Get offers
GET {{baseUrl}}/offers HTTP/1.1

###


# Get by id
GET {{baseUrl}}/offers/11 HTTP/1.1

###

# Update offer
PATCH {{baseUrl}}/offers/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Хабаровск 24",
  "description": "4Cупер новое предложение 2",
  "cityId": 2
}

###

# Delete offer
DELETE {{baseUrl}}/offers/6 HTTP/1.1

###
